### ISSUE TITLE
Changes the names of all wall poles

### ISSUE THREAD

**Issue by 1time** [Kriss321/PowerPoles#2]
As you can see on the images attached as soon as I install the mod all wall poles are getting renamed to MK1 along with their description.

List of the mods installed:

- X3-Signs & Roads
- FoundationIndustries
- Farming Mod
- Light it Up
- Teleporter
- MoarFactory (Assets,Device)
- Covered Conveyor Belt
- More Fences
- Utility Signs

![Screenshot_19](https://user-images.githubusercontent.com/1906377/89404141-66f57680-d711-11ea-8ed3-7eb456a8d774.png)
![Screenshot_21](https://user-images.githubusercontent.com/1906377/89404142-6826a380-d711-11ea-97f5-5fb0f3af9657.png)

**Comment by Kriss321** [comment]
Fixed the porblem in the newest version
