### ISSUE TITLE
Same thing for pipes and hypertubes?

### ISSUE THREAD

**Issue by ror3d** [Kriss321/PowerPoles#5]
There's this other mod called _Floor Hole and Ceiling Logistics_ that does a similar thing for the pipes and hypertubes, as well as conveyor belts, but it adds extra building recipes instead of upgrading the existing ones.

Instead, what you do in this mod for the power poles seems to be just adding the ability for the poles to be on the ground or floor, and I was wondering if the pipelines and hypertubes could be modified in a similar way. I would try to do it myself but I have never used Unreal Engine.

I'm only asking in case this could be a simple change, but if it's more complicated than it seems I totally understand. Thanks!

**Comment by Kriss321** [comment]
It's not that simple. For these I have to create new Meshes and change the logic so that it uses new Meshes instead of moveing one to the right Position.

**Comment by ror3d** [comment]
That's all right then. I thought it might be enough by just rotating the hole mesh. Thank you anyway!
